import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../calculator/domain/models/amortization_month.dart';

/// Service that handles exporting amortization schedules as PDF documents
/// and CSV files, and triggering the native share sheet.
class ExportService {
  /// Creates an [ExportService].
  const ExportService();

  /// Generates a PDF document containing the full amortization schedule
  /// and saves it to a temporary file.
  ///
  /// Returns the path to the generated PDF file.
  ///
  /// Throws an [ExportException] if PDF generation fails.
  Future<String> generatePdf({
    required List<AmortizationMonth> schedule,
    required double loanAmount,
    required double totalInterest,
    required double totalPayment,
    required double emiAmount,
    required double interestRate,
    required int tenureMonths,
  }) async {
    try {
      final pdf = pw.Document();
      final formatter = NumberFormat.currency(
        locale: 'en_IN',
        symbol: '₹ ',
        decimalDigits: 0,
      );

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(32),
          header: (context) => pw.Header(
            level: 0,
            text: 'Amortization Schedule',
          ),
          footer: (context) => pw.Footer(
            title: pw.Text(
              'Generated by EMI Calculator - Smart Loan Planner',
              style: const pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey,
              ),
            ),
          ),
          build: (context) => [
            // ── Loan Summary ──────────────────────
            pw.Header(level: 1, text: 'Loan Summary'),
            pw.TableHelper.fromTextArray(
              headerStyle: const pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 10,
              ),
              headers: ['Parameter', 'Value'],
              data: [
                ['Loan Amount', formatter.format(loanAmount)],
                ['Interest Rate', '${interestRate.toStringAsFixed(1)}%'],
                ['Tenure', '$tenureMonths months'],
                ['Monthly EMI', formatter.format(emiAmount)],
                ['Total Interest', formatter.format(totalInterest)],
                ['Total Payment', formatter.format(totalPayment)],
              ],
            ),
            pw.SizedBox(height: 24),

            // ── Amortization Table ────────────────
            pw.Header(level: 1, text: 'Month-by-Month Breakdown'),
            pw.TableHelper.fromTextArray(
              headerStyle: const pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 8,
              ),
              cellStyle: const pw.TextStyle(fontSize: 7),
              headers: [
                'Month',
                'Opening',
                'EMI',
                'Principal',
                'Interest',
                'Closing',
                'Total Paid',
              ],
              data: schedule.map((entry) {
                return [
                  entry.monthNumber.toString(),
                  formatter.format(entry.openingBalance),
                  formatter.format(entry.emiAmount),
                  formatter.format(entry.principalPaid),
                  formatter.format(entry.interestPaid),
                  formatter.format(entry.closingBalance),
                  formatter.format(entry.totalPaidSoFar),
                ];
              }).toList(),
            ),
          ],
        ),
      );

      // Save to temporary directory.
      final directory = await getTemporaryDirectory();
      final filePath = '${directory.path}/amortization_schedule.pdf';
      final file = File(filePath);
      await file.writeAsBytes(await pdf.save());

      return filePath;
    } catch (e) {
      throw ExportException('Failed to generate PDF: $e');
    }
  }

  /// Generates a CSV string containing the amortization schedule.
  String generateCsv({
    required List<AmortizationMonth> schedule,
  }) {
    final buffer = StringBuffer();

    // Header row.
    buffer.writeln(
      'Month,Opening Balance,EMI Amount,Principal Paid,Interest Paid,'
      'Closing Balance,Total Paid So Far',
    );

    // Data rows.
    for (final entry in schedule) {
      buffer.writeln(
        '${entry.monthNumber},'
        '${entry.openingBalance.toStringAsFixed(2)},'
        '${entry.emiAmount.toStringAsFixed(2)},'
        '${entry.principalPaid.toStringAsFixed(2)},'
        '${entry.interestPaid.toStringAsFixed(2)},'
        '${entry.closingBalance.toStringAsFixed(2)},'
        '${entry.totalPaidSoFar.toStringAsFixed(2)}',
      );
    }

    return buffer.toString();
  }

  /// Saves the [csvContent] to a temporary CSV file and triggers the
  /// native share sheet.
  Future<void> shareCsv(String csvContent) async {
    try {
      final directory = await getTemporaryDirectory();
      final filePath = '${directory.path}/amortization_schedule.csv';
      final file = File(filePath);
      await file.writeAsString(csvContent);

      await Share.shareXFiles(
        [XFile(filePath)],
        subject: 'Amortization Schedule',
      );
    } catch (e) {
      throw ExportException('Failed to share CSV: $e');
    }
  }

  /// Shares the PDF file at [filePath] via the native share sheet.
  Future<void> sharePdf(String filePath) async {
    try {
      await Share.shareXFiles(
        [XFile(filePath)],
        subject: 'Amortization Schedule',
      );
    } catch (e) {
      throw ExportException('Failed to share PDF: $e');
    }
  }
}

/// Exception thrown when an export operation fails.
class ExportException implements Exception {
  /// Creates an [ExportException] with the given [message].
  const ExportException(this.message);

  /// Description of what went wrong.
  final String message;

  @override
  String toString() => 'ExportException: $message';
}
